#-------------------
# OPTIONAL SECTION
#-------------------

# CUDA
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/Snippets/CFindCUDA.cmake)
IF(${CUDA_FOUND})
	INCLUDE_DIRECTORIES(${CUDA_INCLUDE_DIRS})
	SET(EXTERN_LIBS ${EXTERN_LIBS} ${CUDA_LIBRARIES})
	ADD_DEFINITIONS(-DWITH_CUDA)	
ENDIF()
