# This is a basic workflow to help you get started with Actions

name: Test Unity Project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request: 
    branches: [ develop ]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: fimi Develop Test
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        projectPath: ""
        unityVersion:
          - 2020.1.5f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
        testMode:
          - all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      # Test
      - name: Run tests
        id: tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          testMode: ${{ matrix.testMode }}
          projectPath: ${{ matrix.projectPath }}
          customParameters: '-nographics'
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          
      # Upload Test Results
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test results (all modes)
          path: ${{ steps.tests.outputs.artifactsPath }}
